/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SettlementResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SettlementResponse{}

// SettlementResponse struct for SettlementResponse
type SettlementResponse struct {
	CDate string `json:"c_date"`
	Date string `json:"date"`
	Price string `json:"price"`
}

type _SettlementResponse SettlementResponse

// NewSettlementResponse instantiates a new SettlementResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSettlementResponse(cDate string, date string, price string) *SettlementResponse {
	this := SettlementResponse{}
	this.CDate = cDate
	this.Date = date
	this.Price = price
	return &this
}

// NewSettlementResponseWithDefaults instantiates a new SettlementResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSettlementResponseWithDefaults() *SettlementResponse {
	this := SettlementResponse{}
	return &this
}

// GetCDate returns the CDate field value
func (o *SettlementResponse) GetCDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CDate
}

// GetCDateOk returns a tuple with the CDate field value
// and a boolean to check if the value has been set.
func (o *SettlementResponse) GetCDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CDate, true
}

// SetCDate sets field value
func (o *SettlementResponse) SetCDate(v string) {
	o.CDate = v
}

// GetDate returns the Date field value
func (o *SettlementResponse) GetDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Date
}

// GetDateOk returns a tuple with the Date field value
// and a boolean to check if the value has been set.
func (o *SettlementResponse) GetDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Date, true
}

// SetDate sets field value
func (o *SettlementResponse) SetDate(v string) {
	o.Date = v
}

// GetPrice returns the Price field value
func (o *SettlementResponse) GetPrice() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Price
}

// GetPriceOk returns a tuple with the Price field value
// and a boolean to check if the value has been set.
func (o *SettlementResponse) GetPriceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Price, true
}

// SetPrice sets field value
func (o *SettlementResponse) SetPrice(v string) {
	o.Price = v
}

func (o SettlementResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SettlementResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["c_date"] = o.CDate
	toSerialize["date"] = o.Date
	toSerialize["price"] = o.Price
	return toSerialize, nil
}

func (o *SettlementResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"c_date",
		"date",
		"price",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSettlementResponse := _SettlementResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSettlementResponse)

	if err != nil {
		return err
	}

	*o = SettlementResponse(varSettlementResponse)

	return err
}

type NullableSettlementResponse struct {
	value *SettlementResponse
	isSet bool
}

func (v NullableSettlementResponse) Get() *SettlementResponse {
	return v.value
}

func (v *NullableSettlementResponse) Set(val *SettlementResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSettlementResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSettlementResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSettlementResponse(val *SettlementResponse) *NullableSettlementResponse {
	return &NullableSettlementResponse{value: val, isSet: true}
}

func (v NullableSettlementResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSettlementResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


