/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CancelResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CancelResponse{}

// CancelResponse struct for CancelResponse
type CancelResponse struct {
	RetCode string `json:"ret_code"`
	RetMsg string `json:"ret_msg"`
	OrdDate string `json:"ord_date"`
	OrdTime string `json:"ord_time"`
}

type _CancelResponse CancelResponse

// NewCancelResponse instantiates a new CancelResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCancelResponse(retCode string, retMsg string, ordDate string, ordTime string) *CancelResponse {
	this := CancelResponse{}
	this.RetCode = retCode
	this.RetMsg = retMsg
	this.OrdDate = ordDate
	this.OrdTime = ordTime
	return &this
}

// NewCancelResponseWithDefaults instantiates a new CancelResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCancelResponseWithDefaults() *CancelResponse {
	this := CancelResponse{}
	return &this
}

// GetRetCode returns the RetCode field value
func (o *CancelResponse) GetRetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RetCode
}

// GetRetCodeOk returns a tuple with the RetCode field value
// and a boolean to check if the value has been set.
func (o *CancelResponse) GetRetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RetCode, true
}

// SetRetCode sets field value
func (o *CancelResponse) SetRetCode(v string) {
	o.RetCode = v
}

// GetRetMsg returns the RetMsg field value
func (o *CancelResponse) GetRetMsg() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RetMsg
}

// GetRetMsgOk returns a tuple with the RetMsg field value
// and a boolean to check if the value has been set.
func (o *CancelResponse) GetRetMsgOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RetMsg, true
}

// SetRetMsg sets field value
func (o *CancelResponse) SetRetMsg(v string) {
	o.RetMsg = v
}

// GetOrdDate returns the OrdDate field value
func (o *CancelResponse) GetOrdDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrdDate
}

// GetOrdDateOk returns a tuple with the OrdDate field value
// and a boolean to check if the value has been set.
func (o *CancelResponse) GetOrdDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrdDate, true
}

// SetOrdDate sets field value
func (o *CancelResponse) SetOrdDate(v string) {
	o.OrdDate = v
}

// GetOrdTime returns the OrdTime field value
func (o *CancelResponse) GetOrdTime() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrdTime
}

// GetOrdTimeOk returns a tuple with the OrdTime field value
// and a boolean to check if the value has been set.
func (o *CancelResponse) GetOrdTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrdTime, true
}

// SetOrdTime sets field value
func (o *CancelResponse) SetOrdTime(v string) {
	o.OrdTime = v
}

func (o CancelResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CancelResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ret_code"] = o.RetCode
	toSerialize["ret_msg"] = o.RetMsg
	toSerialize["ord_date"] = o.OrdDate
	toSerialize["ord_time"] = o.OrdTime
	return toSerialize, nil
}

func (o *CancelResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ret_code",
		"ret_msg",
		"ord_date",
		"ord_time",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCancelResponse := _CancelResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCancelResponse)

	if err != nil {
		return err
	}

	*o = CancelResponse(varCancelResponse)

	return err
}

type NullableCancelResponse struct {
	value *CancelResponse
	isSet bool
}

func (v NullableCancelResponse) Get() *CancelResponse {
	return v.value
}

func (v *NullableCancelResponse) Set(val *CancelResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCancelResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCancelResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCancelResponse(val *CancelResponse) *NullableCancelResponse {
	return &NullableCancelResponse{value: val, isSet: true}
}

func (v NullableCancelResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCancelResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


