/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fugle-go

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BalanceResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BalanceResponse{}

// BalanceResponse struct for BalanceResponse
type BalanceResponse struct {
	AvailableBalance int32 `json:"available_balance"`
	ExchangeBalance int32 `json:"exchange_balance"`
	StockPreSaveAmount int32 `json:"stock_pre_save_amount"`
}

type _BalanceResponse BalanceResponse

// NewBalanceResponse instantiates a new BalanceResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBalanceResponse(availableBalance int32, exchangeBalance int32, stockPreSaveAmount int32) *BalanceResponse {
	this := BalanceResponse{}
	this.AvailableBalance = availableBalance
	this.ExchangeBalance = exchangeBalance
	this.StockPreSaveAmount = stockPreSaveAmount
	return &this
}

// NewBalanceResponseWithDefaults instantiates a new BalanceResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBalanceResponseWithDefaults() *BalanceResponse {
	this := BalanceResponse{}
	return &this
}

// GetAvailableBalance returns the AvailableBalance field value
func (o *BalanceResponse) GetAvailableBalance() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AvailableBalance
}

// GetAvailableBalanceOk returns a tuple with the AvailableBalance field value
// and a boolean to check if the value has been set.
func (o *BalanceResponse) GetAvailableBalanceOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AvailableBalance, true
}

// SetAvailableBalance sets field value
func (o *BalanceResponse) SetAvailableBalance(v int32) {
	o.AvailableBalance = v
}

// GetExchangeBalance returns the ExchangeBalance field value
func (o *BalanceResponse) GetExchangeBalance() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ExchangeBalance
}

// GetExchangeBalanceOk returns a tuple with the ExchangeBalance field value
// and a boolean to check if the value has been set.
func (o *BalanceResponse) GetExchangeBalanceOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExchangeBalance, true
}

// SetExchangeBalance sets field value
func (o *BalanceResponse) SetExchangeBalance(v int32) {
	o.ExchangeBalance = v
}

// GetStockPreSaveAmount returns the StockPreSaveAmount field value
func (o *BalanceResponse) GetStockPreSaveAmount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.StockPreSaveAmount
}

// GetStockPreSaveAmountOk returns a tuple with the StockPreSaveAmount field value
// and a boolean to check if the value has been set.
func (o *BalanceResponse) GetStockPreSaveAmountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StockPreSaveAmount, true
}

// SetStockPreSaveAmount sets field value
func (o *BalanceResponse) SetStockPreSaveAmount(v int32) {
	o.StockPreSaveAmount = v
}

func (o BalanceResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BalanceResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["available_balance"] = o.AvailableBalance
	toSerialize["exchange_balance"] = o.ExchangeBalance
	toSerialize["stock_pre_save_amount"] = o.StockPreSaveAmount
	return toSerialize, nil
}

func (o *BalanceResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"available_balance",
		"exchange_balance",
		"stock_pre_save_amount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBalanceResponse := _BalanceResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBalanceResponse)

	if err != nil {
		return err
	}

	*o = BalanceResponse(varBalanceResponse)

	return err
}

type NullableBalanceResponse struct {
	value *BalanceResponse
	isSet bool
}

func (v NullableBalanceResponse) Get() *BalanceResponse {
	return v.value
}

func (v *NullableBalanceResponse) Set(val *BalanceResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBalanceResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBalanceResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBalanceResponse(val *BalanceResponse) *NullableBalanceResponse {
	return &NullableBalanceResponse{value: val, isSet: true}
}

func (v NullableBalanceResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBalanceResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


