/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fugle-go

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the KLine type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KLine{}

// KLine struct for KLine
type KLine struct {
	Date string `json:"date"`
	Open float32 `json:"open"`
	High float32 `json:"high"`
	Low float32 `json:"low"`
	Close float32 `json:"close"`
	Volume int32 `json:"volume"`
}

type _KLine KLine

// NewKLine instantiates a new KLine object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKLine(date string, open float32, high float32, low float32, close float32, volume int32) *KLine {
	this := KLine{}
	this.Date = date
	this.Open = open
	this.High = high
	this.Low = low
	this.Close = close
	this.Volume = volume
	return &this
}

// NewKLineWithDefaults instantiates a new KLine object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKLineWithDefaults() *KLine {
	this := KLine{}
	return &this
}

// GetDate returns the Date field value
func (o *KLine) GetDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Date
}

// GetDateOk returns a tuple with the Date field value
// and a boolean to check if the value has been set.
func (o *KLine) GetDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Date, true
}

// SetDate sets field value
func (o *KLine) SetDate(v string) {
	o.Date = v
}

// GetOpen returns the Open field value
func (o *KLine) GetOpen() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Open
}

// GetOpenOk returns a tuple with the Open field value
// and a boolean to check if the value has been set.
func (o *KLine) GetOpenOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Open, true
}

// SetOpen sets field value
func (o *KLine) SetOpen(v float32) {
	o.Open = v
}

// GetHigh returns the High field value
func (o *KLine) GetHigh() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.High
}

// GetHighOk returns a tuple with the High field value
// and a boolean to check if the value has been set.
func (o *KLine) GetHighOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.High, true
}

// SetHigh sets field value
func (o *KLine) SetHigh(v float32) {
	o.High = v
}

// GetLow returns the Low field value
func (o *KLine) GetLow() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Low
}

// GetLowOk returns a tuple with the Low field value
// and a boolean to check if the value has been set.
func (o *KLine) GetLowOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Low, true
}

// SetLow sets field value
func (o *KLine) SetLow(v float32) {
	o.Low = v
}

// GetClose returns the Close field value
func (o *KLine) GetClose() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Close
}

// GetCloseOk returns a tuple with the Close field value
// and a boolean to check if the value has been set.
func (o *KLine) GetCloseOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Close, true
}

// SetClose sets field value
func (o *KLine) SetClose(v float32) {
	o.Close = v
}

// GetVolume returns the Volume field value
func (o *KLine) GetVolume() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Volume
}

// GetVolumeOk returns a tuple with the Volume field value
// and a boolean to check if the value has been set.
func (o *KLine) GetVolumeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Volume, true
}

// SetVolume sets field value
func (o *KLine) SetVolume(v int32) {
	o.Volume = v
}

func (o KLine) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KLine) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["date"] = o.Date
	toSerialize["open"] = o.Open
	toSerialize["high"] = o.High
	toSerialize["low"] = o.Low
	toSerialize["close"] = o.Close
	toSerialize["volume"] = o.Volume
	return toSerialize, nil
}

func (o *KLine) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"date",
		"open",
		"high",
		"low",
		"close",
		"volume",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKLine := _KLine{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varKLine)

	if err != nil {
		return err
	}

	*o = KLine(varKLine)

	return err
}

type NullableKLine struct {
	value *KLine
	isSet bool
}

func (v NullableKLine) Get() *KLine {
	return v.value
}

func (v *NullableKLine) Set(val *KLine) {
	v.value = val
	v.isSet = true
}

func (v NullableKLine) IsSet() bool {
	return v.isSet
}

func (v *NullableKLine) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKLine(val *KLine) *NullableKLine {
	return &NullableKLine{value: val, isSet: true}
}

func (v NullableKLine) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKLine) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


